parserOptions:
  ecmaVersion: 9
  ecmaFeatures:
    jsx: true

env:
  es6: true
  node: true

plugins:
  - import
  - jest
  - react
  - prettier

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:jest/recommended
  - plugin:react/recommended
  - prettier
  - prettier/react

rules:
  import/no-unresolved:
    - error
    - commonjs: true
  prettier/prettier: error

overrides:
  - files: "lib/**/*.js"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: false
  - files: "**/*.test.js"
    env:
      jest: true
  - files: "example/**/*.js"
    env:
      browser: true
