parserOptions:
  ecmaVersion: 9

env:
  es6: true
  node: true

plugins:
  - import
  - prettier

extends:
  - eslint:recommended
  - plugin:import/recommended
  - prettier

rules:
  import/no-unresolved:
    - error
    - commonjs: true
  prettier/prettier: error

overrides:
  - files: "lib/**/*.js"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: false
  - files: "**/*.test.js"
    env:
      jest: true
