name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.12.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run commands
      run: |
        yarn
        yarn lint
        yarn test --colors
      env:
        CI: true
